const Colors = {
    grey : '#bdbdbd',
    black : 'black',
    lightblue :'#007ac3',
    skyblue: '#0978b9', 
    white :'white',
    darkSkyblue : '#007ac3',
    loaderBackGroundColor : '#666666',
    black : '#212121',
    urlColor: '#094369',
    primary:'green',
    activeTextInputColor: '#0c77b7',
    bottomTabIconColorUnfocuesd : '#727473',
    mediumGrey : '#9e9e9e',
    darkGrey: '#bcbcbc',
    lightgrey : '#f0f0f0',
    searchIconColor : '#757575',
    pink : '#b53270',
    favouriteIconColor : '#b8286e',
    videosNameTextColor : '#858585',
    categoriesVideoNameText : '#cccccc',
    viewAllText : '#7d7d7d',
    manuaLUsersText : '#626262',
    deleteIconColor : '#c32c73',
    manualModalWarningText : '#616161',
    manualAdminModalTextColor : '#6aaccd',
    manualModalBackgroundColor : '#c9cacc',
    manualModalTextColor : '#1474af',
    manualAdminModalDisableButtonColor : '#eaedf6',
    manualDetailsDateColor:'#9d9d9d',
    videoViewsBottomWidthColor : '#bebebe',
    videoViewsTextColor : '#5b5b5b',
    addMembersLogoBackGroundColor : '#eaeaea',
    addMembersImageViewBottomWidth : '#c8c8c8',
    addMembersText: '#8e8e8e',
    addFromExistingMembersText : '#606060'

}

export default Colors;